--- CREAREA TABELELOR

--- CREATE SALA_FITNESS(#id_sala, locatie, lant_firma, nr_abonati, nr_traineri, nr_echipamente, nr_telefon, ora_deschidere, ora_inchidere)

CREATE TABLE SALA_FITNESS (
    id_sala NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locatie VARCHAR2(50) NOT NULL,
    lant_firma VARCHAR2(50) NOT NULL,
    nr_abonati INT,
    nr_traineri INT,
    nr_echipamente INT,
    nr_telefon VARCHAR2(10) UNIQUE,
    ora_deschidere DATE,
    ora_inchidere DATE
);

--- CREATE TRAINER(#id_trainer, id_sala, nume, nr_telefon, email, specializare, salariu)

CREATE TABLE TRAINER (
    id_trainer NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sala INT,
    nume VARCHAR2(50) UNIQUE NOT NULL,
    nr_telefon VARCHAR2(10) UNIQUE NOT NULL,
    email VARCHAR2(50) UNIQUE,
    specializare VARCHAR2(50) NOT NULL,
    salariu NUMBER(15, 2),
    FOREIGN KEY (id_sala) REFERENCES SALA_FITNESS(id_sala)
);

--- CREATE MEMBRU(#id_membru, id_sala, id_trainer, nume, email, nr_telefon, data_inscriere)

CREATE TABLE MEMBRU (
    id_membru NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sala INT,
    id_trainer INT,
    nume VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(50) UNIQUE,
    nr_telefon VARCHAR2(10) UNIQUE NOT NULL,
    data_inscriere DATE DEFAULT SYSDATE,
    FOREIGN KEY (id_sala) REFERENCES SALA_FITNESS(id_sala),
    FOREIGN KEY (id_trainer) REFERENCES TRAINER(id_trainer)
);

--- CREATE ECHIPAMENT(#id_echipament, id_sala, denumire, tip_echipament, status, nr_total)

CREATE TABLE ECHIPAMENT (
    id_echipament INT PRIMARY KEY,
    id_sala INT,
    denumire VARCHAR2(50) NOT NULL,
    tip_echipament VARCHAR2(50),
    status VARCHAR2(50),
    nr_total INT,
    FOREIGN KEY (id_sala) REFERENCES SALA_FITNESS(id_sala)
);

CREATE SEQUENCE seq_id_echipament
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

--- CREATE MENTENANTA_ECHIPAMENT(#id_echipament, #data_verificare, stare_verificare, comentarii)

CREATE TABLE MENTENANTA_ECHIPAMENT (
    id_echipament INT,
    data_verificare DATE DEFAULT SYSDATE,
    stare_verificare VARCHAR2(100) NOT NULL,
    comentarii VARCHAR2(500),
    PRIMARY KEY (id_echipament, data_verificare),
    CONSTRAINT fk_mentenanta_echipamanet FOREIGN KEY (id_echipament)
        REFERENCES ECHIPAMENT(id_echipament)
);


--- CREATE SPECIALIZARE(#functie, incadrare, salariu)

CREATE TABLE SPECIALIZARE (
    functie VARCHAR2(50) PRIMARY KEY,
    incadrare VARCHAR2(50),
    salariu NUMBER(10, 2) NOT NULL
);

--- CREATE ANGAJAT(#id_angajat, id_sala, nume, functie, telefon, email)

CREATE TABLE ANGAJAT (
    id_angajat NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sala INT,
    nume VARCHAR2(50) NOT NULL,
    functie VARCHAR2(50) NOT NULL,
    telefon VARCHAR2(10) UNIQUE NOT NULL,
    email VARCHAR2(50) UNIQUE,
    FOREIGN KEY (id_sala) REFERENCES SALA_FITNESS(id_sala),
    FOREIGN KEY (functie) REFERENCES SPECIALIZARE(functie)
);

--- CREATE TIP_ABONAMENT(#tip_abonament)

CREATE TABLE TIP_ABONAMENT (
    tip_abonament VARCHAR2(50) PRIMARY KEY
);

--- CREATE TIP_ABONAMENT_SALA(#tip_abonament, #id_sala, pret)

CREATE TABLE TIP_ABONAMENT_SALA (
    tip_abonament VARCHAR2(50),
    id_sala INT,
    pret NUMBER(10, 2) NOT NULL,
    PRIMARY KEY (tip_abonament, id_sala),
    FOREIGN KEY (tip_abonament) REFERENCES TIP_ABONAMENT(tip_abonament),
    FOREIGN KEY (id_sala) REFERENCES SALA_FITNESS(id_sala)
);

--- CREATE ABONAMENT(#id_abonament, id_sala, id_membru, tip_abonament, activ, data_start, data_end)

CREATE TABLE ABONAMENT (
    id_abonament NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sala INT,
    id_membru INT,
    tip_abonament VARCHAR2(50) NOT NULL,
    activ NUMBER(1),
    data_start DATE NOT NULL,
    data_end DATE,

    FOREIGN KEY (id_sala) REFERENCES SALA_FITNESS(id_sala),
    FOREIGN KEY (id_membru) REFERENCES MEMBRU(id_membru),
    FOREIGN KEY (tip_abonament, id_sala) REFERENCES TIP_ABONAMENT_SALA(tip_abonament, id_sala)
);

--- CREATE PLATI_ABONAMENTE(#id_abonament, id_membru, suma_plata, data_plata, metoda_plata, status_plata)

CREATE TABLE PLATI_ABONAMENTE (
    id_abonament INT PRIMARY KEY,
    id_membru INT,
    suma_plata NUMBER(10, 2),
    data_plata DATE DEFAULT SYSDATE,
    metoda_plata VARCHAR2(50),
    status_plata VARCHAR2(50),
    FOREIGN KEY (id_abonament) REFERENCES ABONAMENT(id_abonament),
    FOREIGN KEY (id_membru) REFERENCES MEMBRU(id_membru)
);

--- CREATE CLASA(#id_clasa, id_sala, id_trainer, nume, capacitate_maxima)

CREATE TABLE CLASA (
    id_clasa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sala INT,
    id_trainer INT,
    nume VARCHAR2(100) NOT NULL,
    capacitate_maxima INT,
    FOREIGN KEY (id_sala) REFERENCES SALA_FITNESS(id_sala),
    FOREIGN KEY (id_trainer) REFERENCES TRAINER(id_trainer)
);

--- CREATE REZERVARE(#id_rezervare, id_membru, data_rezervare, status)

CREATE TABLE REZERVARE (
    id_rezervare NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_membru INT,
    id_clasa INT,
    data_rezervare DATE NOT NULL,
    status VARCHAR2(50),
    FOREIGN KEY (id_membru) REFERENCES MEMBRU(id_membru),
    FOREIGN KEY (id_clasa) REFERENCES CLASA(id_clasa)
);

--- TABELE ASOCIATIVE

--- CREATE MEMBRU_CLASA(#id_membru, #id_clasa, data_inscriere, status_participare, feedback_membru)

CREATE TABLE MEMBRU_CLASA (
    id_membru INT,
    id_clasa INT,
    data_inscriere DATE DEFAULT SYSDATE,
    status_participare VARCHAR2(50),
    feedback_membru NUMBER(5),

    PRIMARY KEY (id_membru, id_clasa),
    FOREIGN KEY (id_membru) REFERENCES MEMBRU(id_membru),
    FOREIGN KEY (id_clasa) REFERENCES CLASA(id_clasa)
);

--- CREATE MEMBRU_ECHIPAMENT(#id_membru, #id_echipament, timp_utilizare, data_ultima_actualizare, intensitate, feedback_utilizare)

CREATE TABLE MEMBRU_ECHIPAMENT (
    id_membru INT,
    id_echipament INT,
    timp_utilizare INT,
    data_ultima_actualizare DATE DEFAULT SYSDATE,
    intensitate VARCHAR2(50),
    feedback_utilizare VARCHAR2(500),

    PRIMARY KEY (id_membru, id_echipament),
    FOREIGN KEY (id_membru) REFERENCES MEMBRU(id_membru),
    FOREIGN KEY (id_echipament) REFERENCES ECHIPAMENT(id_echipament)
);

--- CREATE CLASA_REZERVARE(#id_clasa, #id_rezervare, ora_rezervare, confirmare_trainer, observatii)

CREATE TABLE CLASA_REZERVARE (
    id_clasa INT,
    id_rezervare INT,
    ora_rezervare DATE,
    confirmare_trainer NUMBER(1),
    observatii VARCHAR2(500),

    PRIMARY KEY (id_clasa, id_rezervare),
    FOREIGN KEY (id_clasa) REFERENCES CLASA(id_clasa),
    FOREIGN KEY (id_rezervare) REFERENCES REZERVARE(id_rezervare)
);
